### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_alpha

# 网站 URL ，最后勿加入斜杠
url: http://www.kmqnn.com.cn

# 网站名称
name: 昆明办事处

# 默认标题
title: 全能昆明办事处-昆明保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 昆明保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备09217978号-59</a>


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://test.html9.com/images/alpha-banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，请改QQ号码（每行代码前加入两个空格）
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=4008304555&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:4008304555:41" alt="产品请咨询我" title="产品请咨询我"></a>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=4008304555&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:4008304555:41" alt="产品请咨询我" title="产品请咨询我"></a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：刘先生/任小姐

      **电话**：871-3839473

      **地址**：云南省昆明市盘龙区环城东路36号昆明理工大学新迎校区科技1号楼1楼铺面

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：刘先生/任小姐

      **电话**：871-5420968

      **地址**：云南省昆明市五华区西昌路698号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：刘先生

      **电话**：871-13987163238

      **地址**：云南省昆明市官渡区二环东路583号金马立交桥下

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：李先生

      **电话**：877-13988406068

      **地址**：玉溪市红塔区玉兴路43-5号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：余先生

      **电话**：878-3133901

      **地址**：楚雄市鹿城镇鹿城北路53号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：陈先生

      **电话**：692-4123234

      **地址**：瑞丽市人民路14号


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：云南省昆明市盘龙区环城东路36号昆明理工大学新迎校区科技1号楼1楼铺面
  
  刘先生/任小姐
  
  871-3839473


# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：云南省昆明市盘龙区环城东路36号昆明理工大学新迎校区科技1号楼1楼铺面
  ###联系人：刘先生/任小姐
  ###联系电话：871-3839473

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 102.790704, 25.009390 # auto-updated

# 百度地图框内地址
addr: 地址：云南省昆明市盘龙区环城东路36号昆明理工大学新迎校区科技1号楼1楼铺面

# 右上角电话
telephone: <a href="http://www.qnn.com.cn/" target="_blank">全能保险柜总部</a> 400-830-4555
