### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_alpha

# 网站 URL ，最后勿加入斜杠
url: http://www.qtqnn.com.cn

# 网站名称
name: 全能代理商

# 默认标题
title: 全能代理商

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 保险柜,保险箱,家用保险柜,家用保险箱,保险柜十大品牌,全能保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备</a>


# 首页轮播大图（ - 表示数组项目）
slider:
  - image: http://test.html9.com/images/alpha-banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，请改QQ号码（每行代码前加入两个空格）
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：徐先生

      **电话**：021-58588280

      **地址**：上海省东新区龙东大道5385号龙东大厦首层

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：张小姐

      **电话**：13918010042

      **地址**：上海省浦东新区妙境路872号（近川环南路路口）

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：张先生

      **电话**：13816776700

      **地址**：上海省闸北区沪太路589号（近中北路）

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：郭女士

      **电话**：15800981123

      **地址**：上海省浦东区沪南路近华夏西路红星美凯龙5层

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：刘女士

      **电话**：18202107240

      **地址**：上海省普陀区真北路近怒江北路红星美凯龙北馆二楼

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：胡女士

      **电话**：13671770184

      **地址**：上海省普陀区真北路近怒江北路红星美凯龙南馆负1楼

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：周女士

      **电话**：13816052094

      **地址**：上海省宝山区汶水路近沪太路红星美凯龙一楼

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：牛女士

      **电话**：18917904971

      **地址**：上海省闵行区吴中路近金汇南路剪刀石头布4楼

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：王女士

      **电话**：18202107240

      **地址**：上海省嘉定区曹安路近定边路好美家商场一楼

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：蒋女士

      **电话**：18964103676

      **地址**：上海省徐汇区文定路近蒲汇塘路盛源大地商场二楼


# 侧栏联系（每行代码前加入两个空格）
contact: |
  全能地址：广东省佛山市顺德大良街道凤翔工业区德翔路8号
  
  总部电话：0757-22308180
  
  全国免费服务热线：400-830-4555
  
  售后服务热线：0757-22308180

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：浦东新区龙东大道5385号龙东大厦首层
  ###联系人：徐先生
  ###联系电话：021-58588280

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.28,22.76

# 百度地图框内地址
addr: 地址：浦东新区龙东大道5385号龙东大厦首层

# 右上角电话
telephone: <a href="http://www.qnn.com.cn/" target="_blank">全能保险柜总部</a> 400-830-4555
