### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_alpha

# 网站 URL ，最后勿加入斜杠
url: http://www.zsqnn.com.cn

# 网站名称
name: 中山办事处

# 默认标题
title: 全能中山办事处-中山保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 中山保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备09217978号-5</a>


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://test.html9.com/images/alpha-banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：X先生

      **电话**：0760-88380389/13925339085

      **地址**：广东省中山市起湾道与孙文东路红绿灯路口（汇泉酒店对面)全能保险柜专卖店

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：X先生

      **电话**：0760-13178663039

      **地址**：广东省中山市小榄大信对面民安中路


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：广东省中山市起湾道与孙文东路红绿灯路口（汇泉酒店对面)全能保险柜专卖店
  
  联系人：X先生
  
  联系电话：0760-88380389/13925339085


# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：广东省中山市起湾道与孙文东路红绿灯路口（汇泉酒店对面)全能保险柜专卖店
  ###联系人：X先生
  ###联系电话：0760-88380389/13925339085

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.400061, 22.525551 # auto-updated

# 百度地图框内地址
addr: 地址：广东省中山市起湾道与孙文东路红绿灯路口（汇泉酒店对面)全能保险柜专卖店

# 右上角电话
telephone: <a href="http://www.qnn.com.cn/" target="_blank">全能保险柜总部</a> 400-830-4555
