### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_alpha

# 网站 URL ，最后勿加入斜杠
url: http://www.qzqnn.com.cn

# 网站名称
name: 泉州办事处

# 默认标题
title: 全能泉州办事处-泉州保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 泉州保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备09217978号-47</a>

# 首页轮播大图（大括号包围的块代表一个项目）
# _layout_alpha: 998 x 514px
# _layout_beta: 998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider: [
  {
    image: "http://test.html9.com/images/index-banner03.jpg",
    link: "/b-4538.html",
  },
  {
    image: "http://test.html9.com/images/index-banner03.jpg",
    link: "/b-4538.html",
  },
  {
    image: "http://test.html9.com/images/index-banner03.jpg",
    link: "/b-4538.html",
  },
  {
    image: "http://test.html9.com/images/index-banner03.jpg",
    link: "/b-4538.html",
  },
]

# 侧栏服务，请改QQ号码（每行代码前加入两个空格）
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>

# 专卖店风采（大括号包围的块代表一个项目）
photos: [
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "福建泉州中山南路271号",
    perso: "庄先生	",
    telep: "0595-13505023074",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "福建泉州晋江泉安中路165-169号",
    perso: "庄先生",
    telep: "0595-85617321",
  },
]

# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：福建泉州晋江泉安中路165-169号
  
  联系人：庄先生
  
  联系电话：0595-13505023074
  
  

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：福建泉州晋江泉安中路165-169号
  ###联系人：庄先生
  ###联系电话：0595-13505023074

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 118.591097, 24.816648 # auto-updated

# 百度地图框内地址
addr: 地址：福建泉州晋江泉安中路165-169号

# 右上角电话
telephone: <a href="http://www.qnn.com.cn/" target="_blank">全能保险柜总部</a> 400-830-4555
