### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_alpha

# 网站 URL ，最后勿加入斜杠
url: http://www.lyqnn.cn

# 网站名称
name: 全能代理商

# 默认标题
title: 全能代理商

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 保险柜,保险箱,家用保险柜,家用保险箱,保险柜十大品牌,全能保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备</a>

# 首页轮播大图（大括号包围的块代表一个项目）
# _layout_alpha: 998 x 514px
# _layout_beta: 998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider: [
  {
    image: "http://test.html9.com/images/alpha-banner01.jpg",
    link: "/b-7348.html",
  },
  {
    image: "http://test.html9.com/images/alpha-banner02.jpg",
    link: "/f-2714cke.html",
  },
  {
    image: "http://test.html9.com/images/alpha-banner03.jpg",
    link: "/asafe.html",
  },
  {
    image: "http://test.html9.com/images/alpha-banner04.jpg",
    link: "/fg-5840br.html",
  },
]

# 侧栏服务，请改QQ号码（每行代码前加入两个空格）
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：庄先生

      **电话**：0595-22376321

      **地址**：广东省泉州市中山南路271-273号

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：庄先生

      **电话**：0595-85617321

      **地址**：广东省晋江市泉安中路165-169号

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：陈文波

      **电话**：0595-13705024101

      **地址**：广东省仓山区金祥路金山公交总站正对面

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：陈文波

      **电话**：0595-13705024101

      **地址**：广东省福清市江滨路（江滨医院斜对面）

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：陈文波

      **电话**：0595-13705024101

      **地址**：广东省福清市龙田龙飞路（农业银行正对面）

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：高剑廷

      **电话**：0595-2022137

      **地址**：广东省漳州市芗城区新华南路42号

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：高剑廷

      **电话**：0595-13960165052

      **地址**：广东省漳州市漳浦县朝阳路十字路口若（农业银行正对面）

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：高剑廷

      **电话**：0595-13960165052

      **地址**：广东省漳州集美区杏林杏前路内茂立交内茂公交站旁

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：蔡先生

      **电话**：0595-6266768

      **地址**：广东省福建省莆田市 涵江区涵华西路1783号（商业城国美电器正对面

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：蔡先生

      **电话**：0595-13706098081

      **地址**：广东省莆田市梅园路889号

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：刘先生

      **电话**：0595-3863298

      **地址**：广东省福建宁德市古田县解放 路234号

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：刘先生

      **电话**：0595-3863298

      **地址**：广东省福建宁德市古田县解放 路234号

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：陈先生

      **电话**：0595-18850698333

      **地址**：广东省福建省武夷山市好美家装潢超市

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：张小姐

      **电话**：0595-8806006

      **地址**：广东省福建省三明市三元区新市南路96幢一层5号

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：林先生

      **电话**：0595-13950802826

      **地址**：广东省福建省龙岩市新罗区西城莲花南路


# 侧栏联系（每行代码前加入两个空格）
contact: |
  全能地址：广东省佛山市顺德大良街道凤翔工业区德翔路8号
  
  总部电话：0757-22308180
  
  全国免费服务热线：400-830-4555
  
  售后服务热线：0757-22308180

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：广东省泉州市中山南路271-273号
  ###联系人：庄先生
  ###联系电话：0595-22376321

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.28,22.76

# 百度地图框内地址
addr: 地址：广东省泉州市中山南路271-273号

# 右上角电话
telephone: <a href="http://www.qnn.com.cn/" target="_blank">全能保险柜总部</a> 400-830-4555
