### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_alpha

# 网站 URL ，最后勿加入斜杠
url: http://www.cyqnn.com.cn

# 网站名称
name: 潮阳办事处

# 默认标题
title: 全能潮阳办事处-潮阳保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 潮阳保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备09217978号-13</a>


# 首页轮播大图（ - 表示数组项目）
slider:
  - image: http://test.html9.com/images/alpha-banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，请改QQ号码（每行代码前加入两个空格）
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：林小姐

      **电话**：0754-84485840

      **地址**：广东汕头市潮南区陈店镇湖西广汕公路龙海楼

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：黄先生

      **电话**：0663-6651222

      **地址**：广东省汕头惠来惠城南门大街金盆腔大厦三楼

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：许小姐

      **电话**：0754-85573456

      **地址**：广东省汕头潮南区两英华英东路

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：杨先生

      **电话**：0754-88241240

      **地址**：广东省汕头金平区东厦南路67号

  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：林先生

      **电话**：0754-84440128

      **地址**：广东省汕头市潮阳区贵屿草南路华美路段226-228-234号


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：广东汕头市潮南区陈店镇湖西广汕公路龙海楼
  
  联系人：林小姐
  
  联系电话：0754-84485840
  
  

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：广东汕头市潮南区陈店镇湖西广汕公路龙海楼
  ###联系人：林小姐
  ###联系电话：0754-84485840

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 116.317237, 23.275143 # auto-updated

# 百度地图框内地址
addr: 地址：广东汕头市潮南区陈店镇湖西广汕公路龙海楼

# 右上角电话
telephone: <a href="http://www.qnn.com.cn/" target="_blank">全能保险柜总部</a> 400-830-4555
