### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_alpha

# 网站 URL ，最后勿加入斜杠
url: http://www.tjqnn.com.cn

# 网站名称
name: 天津办事处

# 默认标题
title: 全能天津办事处- 天津保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 天津保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备09217978号-25</a>


# 首页轮播大图（ - 表示数组项目）
slider:
  - image: http://test.html9.com/images/alpha-banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，请改QQ号码（每行代码前加入两个空格）
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/templets/default/images/ex.jpg
    photo: http://test.html9.com/templets/default/images/ex.jpg
    content: |
      **联系人**：", telep: "022-24462510" }, { thumb: "http://test.html9.com/templets/default/images/ex.jpg", photo: "http://test.html9.com/templets/default/images/ex.jpg", addre: "天津和平区和平路新中国商厦3楼", perso: "翟先生", telep: "022-27115769" }, { thumb: "http://test.html9.com/templets/default/images/ex.jpg", photo: "http://test.html9.com/templets/default/images/ex.jpg", addre: "天津南开区卫津路168号", perso: "李经理", telep: "022-13920496658" }, { thumb: "http://test.html9.com/templets/default/images/ex.jpg", photo: "http://test.html9.com/templets/default/images/ex.jpg", addre: "天津河西区黑牛城道谊城公寓8号", perso: "郭先生", telep: "022-28134089" }, { thumb: "http://test.html9.com/templets/default/images/ex.jpg", photo: "http://test.html9.com/templets/default/images/ex.jpg", addre: "天津河东区津塘公路与十四经路交口", perso: "李经理", telep: "022-13920496658" }, { thumb: "http://test.html9.com/templets/default/images/ex.jpg", photo: "http://test.html9.com/templets/default/images/ex.jpg", addre: "天津塘沽区塘沽营口道88号", perso: "李经理", telep: "022-13920496658" }, { thumb: "http://test.html9.com/templets/default/images/ex.jpg", photo: "http://test.html9.com/templets/default/images/ex.jpg", addre: "天津塘沽区塘沽金街", perso: "李经理", telep: "022-13920496658" }, { thumb: "http://test.html9.com/templets/default/images/ex.jpg", photo: "http://test.html9.com/templets/default/images/ex.jpg", addre: "天津武清区武清汽车总站旁", perso: "李经理", telep: "022-13920496658" }, { thumb: "http://test.html9.com/templets/default/images/ex.jpg", photo: "http://test.html9.com/templets/default/images/ex.jpg", addre: "天津西青区卫津南路88号", perso: "李经理", telep: "022-13920496658" }, { thumb: "http://test.html9.com/templets/default/images/ex.jpg", photo: "http://test.html9.com/templets/default/images/ex.jpg", addre: "天津大港区大港油田3号院", perso: "李经理", telep: "022-13920496658

      **电话**：

      **地址**：天津河北区狮子林大街（河北区政府对面）


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：天津和平区和平路新中国商厦3楼
  
  联系人：翟先生
  
  联系电话：022-27115769
  
 
# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：天津和平区和平路新中国商厦3楼
  ###联系人：翟先生
  ###联系电话：022-27115769

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 117.200016, 39.131930 # auto-updated

# 百度地图框内地址
addr: 地址：天津和平区和平路新中国商厦3楼

# 右上角电话
telephone: <a href="http://www.qnn.com.cn/" target="_blank">全能保险柜总部</a> 400-830-4555
