### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_alpha

# 网站 URL ，最后勿加入斜杠
url: http://www.bjqnn.com.cn

# 网站名称
name: 北京办事处

# 默认标题
title: 全能北京办事处-北京保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 北京保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备09217978号-24</a>

# 首页轮播大图（大括号包围的块代表一个项目）
# _layout_alpha: 998 x 514px
# _layout_beta: 998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider: [
  {
    image: "http://www.qnn.com.cn/images/index-banner03.jpg",
    link: "/b-4538.html",
  },
  {
    image: "http://www.qnn.com.cn/images/index-banner03.jpg",
    link: "/b-4538.html",
  },
  {
    image: "http://www.qnn.com.cn/images/index-banner03.jpg",
    link: "/b-4538.html",
  },
  {
    image: "http://www.qnn.com.cn/images/index-banner03.jpg",
    link: "/b-4538.html",
  },
]

# 侧栏服务，请改QQ号码（每行代码前加入两个空格）
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>
  <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&amp;uin=1964506925&amp;site=qq&amp;menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:1964506925:41" alt="产品请咨询我" title="产品请咨询我"></a>

# 专卖店风采（大括号包围的块代表一个项目）
photos: [
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市亚奥北苑路甲13号办公用品区",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市复兴门外大街15号B1层办公用品区",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市成寿寺路308号主楼西区415号",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市翠微路5号翠微大厦5层",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "立汤路186号龙德广场四层办公用品区",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市花园路2号办公用品区",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市清河嘉园东区甲1号(近清河新城)办公用品区",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市中关村大街40号当代商城B1楼",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市北沙滩1号院35号楼地下二层",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市东四环中路191号家居馆B1层/建材馆3层",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市阜成路68号集美2层办公区",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市远大路1号办公用品区",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市北四环东路65号五金超市内",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市远大路1号金源时代购物中心五金超市内",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市西三环南路甲27号五金超市内",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市十八里店大洋坊路106号五金超市内",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市南三环西路58号五金超市内",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市曙光西路206号（三元西桥向北500米路西，国际村南门）",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市北三环西路38号办公用品区",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市西单北大街120号办公用品区",
    perso: "王经理",
    telep: "010-84943881",
  },
  {
    thumb: "http://test.html9.com/templets/default/images/ex.jpg",
    photo: "http://test.html9.com/templets/default/images/ex.jpg",
    addre: "北京市亮马桥路50号办公用品区",
    perso: "王经理",
    telep: "010-84943881",
  },
]

# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：北京市亚奥北苑路甲13号办公用品区
  
  联系人：王经理
  
  联系电话：010-84943881
  

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：北京市亚奥北苑路甲13号办公用品区
  ###联系人：王经理
  ###联系电话：010-84943881

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.28,22.76

# 百度地图框内地址
addr: 地址：北京市亚奥北苑路甲13号办公用品区

# 右上角电话
telephone: <a href="http://www.qnn.com.cn/" target="_blank">全能保险柜总部</a> 400-830-4555


### 下面的不用改 ###

# 产品图片网址，以斜杠结尾
p_img_cdn: http://test.html9.com/image-pro/

# 分类
product_categories: [
{
  name: "家用系列",
  cats: [
    ["feng-sheng-shui-qi","风生水起"],
    ["quan-neng-jin-ku","全能金库"],
    ["ke-la-zhen-cang","可拉珍藏"],
    ["gang-tie-xia","钢铁侠"],
    ["gao-er-fu","高尔夫"],
    ["xin-huang-guan","新皇冠"],
    ["tie-jin-gang","铁金钢"],
    ["gang-jiang-jun","钢将军"],
    ["tie-guan-jia","铁管家"],
    ["lan-jing-ling","蓝精灵"],
    ["ping-guo","苹果系列"],
    ["zhen-cang","珍藏系列"],
    ["yi-dong","逸动系列"],
    ["zhi-wen","指纹系列"],
    ["cang-bao","藏宝系列"],
    ["an-gu","安固系列"],
    ["qian-qiang","嵌墙系列"]
  ]
},
{
  name: "商用系列",
  cats: [
    ["feng-sheng-shui-qi","风生水起"],
    ["quan-neng-jin-ku","全能金库"],
    ["gang-tie-xia","钢铁侠"],
    ["gao-er-fu","高尔夫"],
    ["xin-huang-guan","新皇冠"],
    ["tie-jin-gang","铁金钢"],
    ["gang-jiang-jun","钢将军"],
    ["tie-guan-jia","铁管家"],
    ["lan-jing-ling","蓝精灵"],
    ["zhi-wen","指纹系列"],
    ["cang-bao","藏宝系列"],
    ["an-gu","安固系列"],
    ["di-cang","地藏系列"],
    ["tie-guan-yin-fang-huo","铁观音防火"]
  ]
},
{
  name: "办公系列",
  cats: [
    ["wei-na-si","维纳斯"],
    ["shuang-kai-men","双开门"],
    ["chou-ti-shi","抽屉式"]
  ]
},
{
  name: "酒店系列",
  cats: [
    ["qnnsafe-ke-fang-gui","QNNSAFE客房柜"],
    ["hotsafe-ke-fang-gui","HOTSAFE客房柜"],
    ["qian-ting-bao-guan-xiang","前厅保管箱"],
    ["qian-ting-tou-bi-gui","前厅投币柜"]
  ]
},
{
  name: "金融系列",
  cats: [
    ["jin-ku-men","金库门"],
    ["yi-dong-jin-ku","移动金库"],
    ["yin-xing-bao-guan-xiang","银行保管箱"],
    ["xian-jin-tou-bao-ji","现金投包机"],
    ["atm-gui-yuan-ji","ATM柜员机"],
    ["you-zhan-tou-bi-gui","油站投币柜"]
  ]
},
{
  name: "枪弹系列",
  cats: [
    ["qiang-dan-gui","枪弹柜"],
    ["dan-yao-gui","弹药柜"],
    ["zhi-neng-qiang-dan-gui","智能枪弹柜"],
    ["chu-wu","储物系列"],
    ["zhi-neng-bao-mi-gui","智能保密柜"],
    ["yue-chi-gui","钥匙柜"],
    ["ji-cun-gui","寄存柜"],
  ]
},{
  name: "物流系列",
  cats: [
    ["cun-qu-gui","存取柜"]
  ]
}
]

# 生成的网站不包含的文件
exclude: ['README.md']

# markdown
markdown: rdiscount

# 链接格式
permalink: :title.html

# 分页项目数，忽略
paginate: 20
