### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_alpha

# 网站 URL ，最后勿加入斜杠
url: http://www.csqnn.cn

# 网站名称
name: 长沙办事处

# 默认标题
title: 全能长沙办事处-长沙保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 长沙保险柜

# 版权，请改备案号
copy: 版权所有 &copy; 1999-2013 广东安能保险柜制造有限公司 <a href="http://www.miibeian.gov.cn/" target="_blank">粤ICP备09217978号-34</a>

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://test.html9.com/images/alpha-banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：曾先生

      **电话**：0731-84699631

      **地址**：湖南长沙市高桥火焰文体城一区一栋5号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：欧阳先生

      **电话**：0730-4369535

      **地址**：湖南岳阳市巴陵中路428-430号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：伍先生

      **电话**：0734-4369535

      **地址**：湖南耒阳市城北路

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：欧阳先生

      **电话**：0731-58229511

      **地址**：湖南湘潭市韶山西路22号（霖园天桥旁）号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：刘先生

      **电话**：0737-4208798

      **地址**：湖南益阳市桃花仓西路1078-1080号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：罗先生

      **电话**：0739-2988988

      **地址**：湖南邵东县兴和大道60-62号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：廖先生

      **电话**：0735-2266339

      **地址**：湖南郴州市苏仙区苏园路2号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：陈小姐

      **电话**：0745-2718268

      **地址**：湖南湖南怀化市迎丰中路284号


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：湖南省长沙市高桥火焰文体城一区一栋5号
  
  联系人：曾先生
  
  联系电话：0731-84699631


# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：湖南省长沙市高桥火焰文体城一区一栋5号
  ###联系人：曾先生
  ###联系电话：0731-84699631

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.025373, 28.180262 # auto-updated

# 百度地图框内地址
addr: 地址：湖南省长沙市高桥火焰文体城一区一栋5号

# 右上角电话
telephone: <a href="http://www.qnn.com.cn/" target="_blank">全能保险柜总部</a> 400-830-4555
