### 请小心更改配置文件 ###

# 模板、主题、版式
# _layout_alpha , _layout_beta , _layout_gamma , _layout_delta
layouts: _layout_gamma

# 网站 URL ，最后勿加入斜杠
url: http://www.gddgqnn.com

# 网站名称
name: 广东东莞办事处

# 默认标题
title: 全能保险柜广东东莞办事处-东莞保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 默认关键词
keywords: 东莞保险柜

# 备案号
beian: 粤ICP备09217978号-3

# 自定首页公司简介段落
# homepage_about: |
#   全能保险柜是以从事保险柜（箱）等安防产品为主的现代化保险柜...

# 自定关于我们页面内容，默认是读取 _includes/about_company.md
# about: |
#   广东安能保险柜制造有限公司是...

#   公司控股工业集团创始于1935年...

#   经过多年的持续发展，公司已跻身...


# 首页轮播大图（ - 表示数组项目）
# _layout_alpha: 998 x 514px
# _layout_beta:  998 x 350px
# _layout_gamma: 998 x 350px
# _layout_delta: 720 x 288px
slider:
  - image: http://test.html9.com/images/alpha-banner01.jpg
    link:  /b-7348.html

  - image: http://test.html9.com/images/alpha-banner02.jpg
    link:  /f-2714cke.html

  - image: http://test.html9.com/images/alpha-banner03.jpg
    link:  /asafe.html

  - image: http://test.html9.com/images/alpha-banner04.jpg
    link:  /fg-5840br.html


# 侧栏服务，格式如下：
# 企业QQ：<a class="enterprise_qq" href="#">客户咨询</a>
# 个人QQ：<a class="individual_qq" data-qq="这里填写QQ号码" href="#">客户咨询</a>
service: |
  <p>客户咨询时间：早上8:00到下午17:30</p>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>
  <a class="enterprise_qq" href="#">客户咨询</a>


# 专卖店风采（ - 表示数组项目，content 用 markdown 格式）
photos:
  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-23036190

      **地址**：广东省东莞市南城区莞太路段23号鸿禧大厦103

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-23397993

      **地址**：广东省东莞市东城区东纵大道加油站旁

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-85539263

      **地址**：广东省东莞市长安镇德政中路146号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-83339639

      **地址**：广东省东莞市常平镇口岸大道7号（东莞火车站旁）

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-81511330

      **地址**：广东省东莞市虎门镇虎门大道156号（计生办对面）

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞市莞城区东兴路170号罗沙大厦

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-87933155

      **地址**：广东省东莞市塘厦镇新园大厦B座1楼（水电三局对面）

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞市虎门镇人民路167号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞市长安镇358省道388号-394号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞市长安镇地王广场镇政府对面时尚电器城

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞市塘厦镇大道北115号

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞南城区南城科技大道（家居装饰城对面）

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞市常平镇金美村金兴工业区（常朗大道）

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞市莞城区东城中路美新家居中心二楼

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞市虎门镇虎门人民南路虎门大道146

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞市莞城区东城中路光辉大厦1-6楼

  - thumb: http://test.html9.com/images/qnnsafe01.jpg
    photo: http://test.html9.com/images/qnnsafe01.jpg
    content: |
      **联系人**：郑经理

      **电话**：0769-13549483538

      **地址**：广东省东莞市虎门镇虎门大道


# 侧栏联系（每行代码前加入两个空格）
contact: |
  地址：广东省东莞市南城区莞太路段23号鸿禧大厦103
  
  联系人：郑经理
  
  联系电话：0769-23036190
  

# 联系页（每行代码前加入两个空格）
contacthtml: |
  ###地址：广东省东莞市南城区莞太路段23号鸿禧大厦103
  ###联系人：郑经理
  ###联系电话：0769-23036190

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.751877, 23.030645 # auto-updated

# 百度地图框内地址
addr: 地址：广东省东莞市南城区莞太路段23号鸿禧大厦103
